// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uljqgubhxwwruuvvlpyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsanFndWJoeHd3cnV1dnZscHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjE0MjQsImV4cCI6MjA1NzYzNzQyNH0.XH6_hH91AUwqfQ10mnIaY2EO51uJrN4afDJRj8_m5yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);